//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.261
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GPG4OutlookLib.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class messages : global::System.Configuration.ApplicationSettingsBase {
        
        private static messages defaultInstance = ((messages)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new messages())));
        
        public static messages Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Please provide a valid gpg.exe path.")]
        public string pathError {
            get {
                return ((string)(this["pathError"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Recipient is required before encrypting data.")]
        public string recipientError {
            get {
                return ((string)(this["recipientError"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Unable to find gpg.exe. Please verify the installation path and executable.")]
        public string pathExeError {
            get {
                return ((string)(this["pathExeError"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("A time out event occurred while executing the GPG program.\t")]
        public string timeOutError {
            get {
                return ((string)(this["timeOutError"]));
            }
            set {
                this["timeOutError"] = value;
            }
        }
    }
}
